---
title: "data_cleaning"
author: "Zhenyu Gu"
date: "12/8/2018"
output: html_document
---

```{r}
price = function(string){
  return(as.numeric(strsplit(string," ")[[1]][1]))
}
contract = function(string){
  return(as.numeric(strsplit(string," ")[[1]][3]))
}
order = function(string){
  return(as.numeric(strsplit(string,"[()]")[[1]][2]))
}

toSeconds = function(file){
  
  df = read.csv(file)
  buy_input = as.matrix(split(df,df$Side)[['BUY']])
  sell_input = as.matrix(split(df,df$Side)[['SELL']])
  buy_vol = buy_sum = buy_contr = buy_ord = 0
  buy_output = matrix(ncol=8)
  
  for (i in 1:nrow(buy_input)){
    buy_vol = buy_vol + sum(unlist(lapply(buy_input[i,4:13], contract)))
    buy_ord = buy_ord + sum(unlist(lapply(buy_input[i,4:13], order)))
    buy_contr = buy_contr + sum(unlist(lapply(buy_input[i,4:13], contract)))
    buy_sum = buy_sum + sum(unlist(lapply(buy_input[i,4:13], price))
                            * unlist(lapply(buy_input[i,4:13], contract)))
    if (i==1){
      buy_time = as.numeric(buy_input[i,1])%/%1000
      buy_open = price(unlist(buy_input[i,4]))
      buy_low = min(unlist(lapply(buy_input[i,4:13], price)))
      buy_high = max(unlist(lapply(buy_input[i,4:13], price)))
    }else if(i!=1 & as.numeric(buy_input[i,1])%/%1000 > as.numeric(buy_input[i-1,1])%/%1000){
      buy_time = as.numeric(buy_input[i,1])%/%1000
      buy_open = price(unlist(buy_input[i,4]))
      buy_low = min(unlist(lapply(buy_input[i,4:13], price)))
      buy_high = max(unlist(lapply(buy_input[i,4:13], price)))
    }else{
      row_low = min(unlist(lapply(buy_input[i,4:13], price)))
      row_high = max(unlist(lapply(buy_input[i,4:13], price)))
      if(row_low < buy_low) buy_low = row_low
      if(row_high > buy_high) buy_high = row_high
    }
    if (i==nrow(buy_input)){
      buy_close = price(unlist(buy_input[i,13]))
      buy_weighted_avg = buy_sum / buy_contr
      buy_output = rbind(buy_output, c(buy_time,buy_open,buy_close,buy_low,buy_high,buy_vol,buy_ord,buy_weighted_avg))
      buy_vol = buy_sum = buy_contr = buy_ord = 0
    }else if(i!=nrow(buy_input) & as.numeric(buy_input[i,1])%/%1000 < as.numeric(buy_input[i+1,1])%/%1000){
      buy_close = price(unlist(buy_input[i,13]))
      buy_weighted_avg = buy_sum / buy_contr
      buy_output = rbind(buy_output, c(buy_time,buy_open,buy_close,buy_low,buy_high,buy_vol,buy_ord,buy_weighted_avg))
      buy_vol = buy_sum = buy_contr = buy_ord = 0
    }
  }
  buy_output = buy_output[-1,]
  colnames(buy_output) = c('time','buy_open','buy_close','buy_low','buy_high','buy_volume','buy_ord','buy_weighted_avg')
  
  sell_vol = sell_sum = sell_contr = sell_ord = 0
  sell_output = matrix(ncol=8)
  
  for (i in 1:nrow(sell_input)){
    sell_vol = sell_vol + sum(unlist(lapply(sell_input[i,4:13], contract)))
    sell_ord = sell_ord + sum(unlist(lapply(sell_input[i,4:13], order)))
    sell_contr = sell_contr + sum(unlist(lapply(sell_input[i,4:13], contract)))
    sell_sum = sell_sum + sum(unlist(lapply(sell_input[i,4:13], price))
                            * unlist(lapply(sell_input[i,4:13], contract)))
    if (i==1){
      sell_time = as.numeric(sell_input[i,1])%/%1000
      sell_open = price(unlist(sell_input[i,4]))
      sell_low = min(unlist(lapply(sell_input[i,4:13], price)))
      sell_high = max(unlist(lapply(sell_input[i,4:13], price)))
    }else if(i!=1 & as.numeric(sell_input[i,1])%/%1000 > as.numeric(sell_input[i-1,1])%/%1000){
      sell_time = as.numeric(sell_input[i,1])%/%1000
      sell_open = price(unlist(sell_input[i,4]))
      sell_low = min(unlist(lapply(sell_input[i,4:13], price)))
      sell_high = max(unlist(lapply(sell_input[i,4:13], price)))
    }else{
      row_low = min(unlist(lapply(sell_input[i,4:13], price)))
      row_high = max(unlist(lapply(sell_input[i,4:13], price)))
      if(row_low < sell_low) sell_low = row_low
      if(row_high > sell_high) sell_high = row_high
    }
    if (i==nrow(sell_input)){
      sell_close = price(unlist(sell_input[i,13]))
      sell_weighted_avg = sell_sum / sell_contr
      sell_output = rbind(sell_output, c(sell_time,sell_open,sell_close,sell_low,sell_high,sell_vol,sell_ord,sell_weighted_avg))
      sell_vol = sell_sum = sell_contr = sell_ord = 0
    }else if(i!=nrow(sell_input) & as.numeric(sell_input[i,1])%/%1000 < as.numeric(sell_input[i+1,1])%/%1000){
      sell_close = price(unlist(sell_input[i,13]))
      sell_weighted_avg = sell_sum / sell_contr
      sell_output = rbind(sell_output, c(sell_time,sell_open,sell_close,sell_low,sell_high,sell_vol,sell_ord,sell_weighted_avg))
      sell_vol = sell_sum = sell_contr = sell_ord = 0
    }
  }
  sell_output = sell_output[-1,]
  colnames(sell_output) = c('time','sell_open','sell_close','sell_low','sell_high','sell_volume','sell_ord','sell_weighted_avg')
  result = merge(buy_output, sell_output, by.x='time', by.y='time', all.x=TRUE, all.y=TRUE)
  write.csv(result, file = "concat.csv",row.names=FALSE) # change output file name here
}
```

```{r}
toSeconds("Workbook1.csv") # change input file name here
```

