---
title: "Exploratory Analysis"
author: "Zihe Wang"
date: "12/6/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(purrr)
library(data.table)
library(dplyr)
library(readr)

t1_raw <- fread("data/Ticker1.csv")
t1_directions <- fread("data/Ticker1_label.csv")
t1_raw$Timestamp <- floor(t1_raw$Timestamp / 1000)
t1_features <- t1_features[, -c("Timestamp")]


test <- '2062.75000000 x 145 (61)'

library(tidyr)
get_v <- function(string) {
  contract_orders <- strsplit(string, 'x')[[1]][2]
  contract <- strsplit(contract_orders, '\\(')[[1]][1]
  return(as.numeric(contract))
}

get_p <- function(string) {
  prices <- as.numeric(strsplit(string, 'x')[[1]][1])
  return(prices)
}

get_wv <- function(string) {
  parsed <- strsplit(string, 'x')[[1]]
  prices <-  as.numeric(parsed[1])
  contract <- as.numeric(strsplit(parsed[2], '\\(')[[1]][1])
  return(prices * contract)
}

get_o <- function(string) {
  parsed <- strsplit(string, 'x')[[1]]
  parsed2 <- strsplit(parsed[2], '\\(')
  orders <-parse_number(parsed2[[1]][2])
  return(orders)
}

# my_parse_str <- function(column){
#   parsed <- strsplit(column, 'x')[[1]]
#   prices <-  as.numeric(parsed[1])
#   parsed2 <- strsplit(parsed[2], '\\(')
#   contract <- as.numeric(parsed2[[1]][1])
#   orders <-parse_number(parsed2[[1]][2])
#   return(c(prices, contract, orders))
# }

# cluster on Windows
library(parallel)
process_data <- function(raw_dat){
  raw_dat$Timestamp <- floor(raw_dat$Timestamp / 1000)
  buy_raw <- raw_dat[raw_dat$Side == 'BUY', ]
  sell_raw <- raw_dat[raw_dat$Side == 'SELL', ]
  raw_list <- list(buy_raw, sell_raw)
  cores <- detectCores(logical = FALSE)
  print("apply begin")
  ret_dat <- mclapply(1:2, 
                      FUN = function(i){
                        dat <- raw_list[[i]]
                        ret <- dat %>% rowwise() %>% 
                                  mutate(open = get_p(Level1),
                                         volumns = sum(sapply(c(Level1, Level2, Level3, Level4, Level5, Level6, Level7, Level8, Level9, Level10), get_v)),
                                         order = sum(sapply(c(Level1, Level2, Level3, Level4, Level5, Level6, Level7, Level8, Level9, Level10), get_o)),
                                         weight_sum = sum(sapply(c(Level1, Level2, Level3, Level4, Level5, Level6, Level7, Level8, Level9,Level10), get_wv)),
                                         highest = max(sapply(c(Level1, Level2, Level3, Level4, Level5, Level6, Level7, Level8, Level9,Level10), get_p)),
                                         lowest = apply(sapply(c(Level1, Level2, Level3, Level4, Level5, Level6, Level7, Level8, Level9,Level10), get_p)), 1, 
                                                        FUN = function(x) {min(x[x > 0])}) %>%
                                  group_by(Timestamp, Side) %>% 
                                  summarise(
                                    O = open[1],
                                    C = tail(open, 1),
                                    H = max(highest),
                                    L = min(lowest),
                                    V = sum(volumns),
                                    Orders = sum(order),
                                    WS = sum(weight_sum) / V)
                        return(ret)
                      },
                      mc.cores = 2
                      )
  print("start merging")
  ret <- merge(ret_dat[[1]], ret_dat[[2]], by="Timestamp", all=TRUE)
  #write_csv(ret, name)
  return(ret)
}
test_data <- t1_raw[300000:3355326,]
ret <- process_data(test_data)
#begin: 1:53
#end: 
```

叶佬要的
```{r}

test <- t1_raw[1:50000,]
dat_p <- test[test$Side == 'SELL', ] %>% mutate_at(vars(Level1:Level10), funs(p = get_p, v = get_v, o = get_o, ws = get_wv))
close_prices <- dat_p %>% group_by(Timestamp, Side) %>% summarise_at(vars(Level1_p:Level10_p), funs(C = tail), n=1) %>% select(c(Level1_p_C:Level10_p_C))
sum_prices <- dat_p %>% group_by(Timestamp, Side) %>% summarise_at(vars(Level1_ws:Level10_ws), funs(sum = sum)) %>% select(c(Level1_ws_sum:Level10_ws_sum))
sum_volumns <- dat_p %>% group_by(Timestamp, Side) %>% summarise_at(vars(Level1_v:Level10_v), funs(sum = sum)) %>% select(c(Level1_v_sum:Level10_v_sum))
ret <- cbind(close_prices, sum_prices[,-1])
ret <- cbind(ret, sum_volumns[,-1])

head(test)
ret <- dat %>%
          group_by(Timestamp, Side) %>% 
          summarise(
            O = open[1],
            C = tail((close), 1),
            H = max(highest),
            L = min(lowest),
            V = sum(volumns),
            Orders = sum(order),
            WS = sum(weight_sum) / V)

t1_features <- fread("data/Ticker1.csv")
t2_features <- fread("data/Ticker2.csv")
t3_features <- fread("data/Ticker3.csv")
t4_features <- fread("data/Ticker4.csv")
process_data(t1_features, "t1_dat")
process_data(t2_features, "t2_dat")
process_data(t3_features, "t3_dat")
process_data(t4_features, "t4_dat")
```


叶佬 data processing
```{r}
library(data.table) # fread
# library(bit64) # sell_volume
library(imputeTS) # na.replace
ticker1 <- fread("t1_dat.csv")
# ticker1$sell_volume <- as.numeric(ticker1$sell_volume)
ticker2 <- fread("data/ticker_2.csv")
ticker3 <- fread("data/ticker_3.csv")
ticker4 <- fread("data/ticker_4.csv")
ticker1_label <- fread("data/Ticker1_label.csv")
ticker2_label <- fread("data/Ticker2_label.csv")
ticker3_label <- fread("data/Ticker3_label.csv")
ticker4_label <- fread("data/Ticker4_label.csv")
head(ticker1)
ticker1[,c(3:6,9, 11:14, 16)] <- na.interpolation(ticker1[,c(3:6,9, 11:14, 16)], option = "linear")
ticker2[,c(2:5, 8:12, 15)] <- na.interpolation(ticker2[,c(2:5, 8:12, 15)], option = "linear")
ticker3[,c(2:5, 8:12, 15)] <- na.interpolation(ticker3[,c(2:5, 8:12, 15)], option = "linear")
ticker4[,c(2:5, 8:12, 15)] <- na.interpolation(ticker4[,c(2:5, 8:12, 15)], option = "linear")
ticker1 <- na.replace(ticker1, 0)
ticker2 <- na.replace(ticker2, 0)
ticker3 <- na.replace(ticker3, 0)
ticker4 <- na.replace(ticker4, 0)
```
叶式筛法
```{r}
library(reshape2)
library(dplyr)
library(data.table)
library(readr)
library(tidyr)
extract_numeric(years)
parse_number(years)
raw1 <- fread("data/Ticker1.csv")
raw1$s <- raw1$Timestamp%/%1000
raw1$h <- floor(raw1$s/10000)
raw1$m <- floor((raw1$s-raw1$h*10000)/100)
raw1$s <- (raw1$s-raw1$h*10000-raw1$m*100)

Price = as.data.frame(apply(raw1[, c(4:13)], 2, colsplit, pattern = "x", names = c("Price", "right")))
Volume = as.data.frame(apply(Price[,seq(2, 20, 2)], 2, colsplit, pattern = "[(]", names = c("Volume", "Order")))
Orders = as.data.frame(apply(Volume[,seq(2, 20, 2)], 2, extract_numeric))
Volume = Volume[,seq(1, 20, 2)]
Price = Price[,seq(1, 20, 2)]
P.V <- cbind(Price, Volume)
P.V.O <- cbind(P.V, Orders)


data <- raw1[,-c(4:13)]
data <- cbind(data, P.V.O)
data$Level1.Sum <- data$Level1.Price * data$Level1.right.Volume
data$Level2.Sum <- data$Level2.Price * data$Level2.right.Volume
data$Level3.Sum <- data$Level3.Price * data$Level3.right.Volume
data$Level4.Sum <- data$Level4.Price * data$Level4.right.Volume
data$Level5.Sum <- data$Level5.Price * data$Level5.right.Volume
data$Level6.Sum <- data$Level6.Price * data$Level6.right.Volume
data$Level7.Sum <- data$Level7.Price * data$Level7.right.Volume
data$Level8.Sum <- data$Level8.Price * data$Level8.right.Volume
data$Level9.Sum <- data$Level9.Price * data$Level9.right.Volume
data$Level10.Sum <- data$Level10.Price * data$Level10.right.Volume
data <- data[, -1]

data_buy <- data[data$Side == "BUY",]
data_sell <- data[data$Side == "SELL",]
t1_buy_p <- data_buy %>% group_by(Ticker, Side, s, h, m) %>% 
                   summarise_at(vars(Level1.Price:Level10.Price), funs(O=first, C=last))
t1_buy_v <- data_buy %>% group_by(Ticker, Side, s, h, m) %>% 
                   summarise_at(vars(Level1.right.Volume:Level10.right.Volume), funs(v=sum))
t1_buy_o <- data_buy %>% group_by(Ticker, Side, s, h, m) %>% 
                   summarise_at(vars(Level1.right.Order:Level10.right.Order), funs(o=sum))
t1_buy_ws <- data_buy %>% group_by(Ticker, Side, s, h, m) %>% 
                   summarise_at(vars(Level1.Sum:Level10.Sum), funs(ws=sum))
t1_buy_v <- t1_buy_v[,-(1:5)]
t1_buy_o <- t1_buy_o[,-(1:5)]
t1_buy_ws <- t1_buy_ws[,-(1:5)]
t1_buy <- merge(t1_buy_p, t1_buy_o)
t1_buy <- merge(t1_buy, t1_buy_v)
t1_buy <- merge(t1_buy, t1_buy_ws)


t1_sell_p <- data_sell %>% group_by(Ticker, Side, s, h, m) %>% 
                   summarise_at(vars(Level1.Price:Level10.Price), funs(O=first, C=last))
t1_sell_v <- data_sell %>% group_by(Ticker, Side, s, h, m) %>% 
                   summarise_at(vars(Level1.right.Volume:Level10.right.Volume), funs(v=sum))
t1_sell_o <- data_sell %>% group_by(Ticker, Side, s, h, m) %>% 
                   summarise_at(vars(Level1.right.Order:Level10.right.Order), funs(o=sum))
t1_sell_ws <- data_sell %>% group_by(Ticker, Side, s, h, m) %>% 
                   summarise_at(vars(Level1.Sum:Level10.Sum), funs(ws=sum))
t1_sell_v <- t1_sell_v[,-(1:5)]
t1_sell_o <- t1_sell_o[,-(1:5)]
t1_sell_ws <- t1_sell_ws[,-(1:5)]
t1_sell <- merge(t1_sell_p, t1_sell_o)
t1_sell <- merge(t1_sell, t1_sell_v)
t1_sell <- merge(t1_sell, t1_sell_ws)
t1_dat <- merge(t1_buy, t1_sell, by = c("Ticker", "s", "h", "m"), all = TRUE)
t1_dat <- fread('ticker1_processed.csv')
t1_dat <- t1_dat[, -c(1, 6, 57)]
t1_dat[,5:104] <- na.interpolation(t1_dat[,5:104], option = "linear")
write.csv(t1_dat, "ticker1_processed.csv")
t1_dat <- t1_dat[, -c(5, 56)]
t1_dat[,5:104] <- apply(t1_dat[,5:104], 2, log)
t1_label <- fread("data/Ticker1_label.csv")
library(randomForest)

```


